name: J.A. Villegas 
description: Estudiante universitario
github: http://www.github.com/JAntonioVR
twitter: http://www.twitter.com/JAntonio_VR
instagram: http://www.instagram.com/juanantonio_79
email: juanantoniovr98[at]gmail.com
location: 
## disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
